# Generated by Django 5.1.2 on 2024-11-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_landscape',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters/poster_landscape/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_portrait',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters/poster_portrait/'),
        ),
    ]
