services:
  # Redis service
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # PostgreSQL service
  postgres:
    image: "postgres:15"
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Django application service
  web:
    build: .
    command: /entrypoint.sh  # Use the entrypoint script instead of running the server directly
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres  # Ensure PostgreSQL is ready before starting the Django app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
