# Generated by Django 5.1.2 on 2025-02-07 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_number', models.CharField(max_length=10)),
                ('num_rows', models.PositiveSmallIntegerField()),
                ('num_cols', models.PositiveSmallIntegerField()),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theatres.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_position', models.PositiveSmallIntegerField()),
                ('column_position', models.PositiveSmallIntegerField()),
                ('seat_label', models.CharField(blank=True, help_text='Eg., A1, B2', max_length=10, unique=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theatres.screen')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('screen', 'seat_label'), name='unique_screen_seat_label')],
            },
        ),
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(fields=('theatre', 'screen_number'), name='unique_theatre_screen_number'),
        ),
    ]
